/**
 * Todo example
 * The amazing API framework
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NoteEntity } from './noteEntity';

export interface GetManyNoteEntityResponseDto { 
    data: Array<NoteEntity>;
    count: number;
    total: number;
    page: number;
    pageCount: number;
}